/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Banco;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author tomas
 */
public class Transferencia extends javax.swing.JFrame {

    
    Registro registro;
    login login;
    DateFormat modificarFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    
    public Transferencia() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public Transferencia(Registro registro,login login){
        initComponents();
        this.registro = registro;
        this.login = login;
        Operaciones op = new Operaciones(registro, login);
        txtAreaHistorialT.setText(registro.listaClientes.get(op.codigo).mostrarTransferencias());
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTransferencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaHistorialT = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 98, 255));
        jPanel1.setInheritsPopupMenu(true);

        jLabel1.setBackground(new java.awt.Color(85, 114, 254));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSFERENCIAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        btnTransferencia.setBackground(new java.awt.Color(253, 254, 248));
        btnTransferencia.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnTransferencia.setForeground(new java.awt.Color(102, 102, 102));
        btnTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banco/mas_icon (Personalizado).png"))); // NOI18N
        btnTransferencia.setText("Nueva tansferencia");
        btnTransferencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtAreaHistorialT.setColumns(20);
        txtAreaHistorialT.setRows(5);
        jScrollPane1.setViewportView(txtAreaHistorialT);

        jLabel2.setBackground(new java.awt.Color(85, 114, 254));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HISOTRIAL");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed

        String[] bancos = {"Mismo banco", "Otro banco", "Cancelar"};
        float montoR = 0;
        int banco = -1;
        String transf = "";
        try{
            
            Operaciones op = new Operaciones(registro, login);
            banco = JOptionPane.showOptionDialog(rootPane, "Transferencias a otro banco"
                    + "\ntienen un recargo de 5 %", "BANCO", JOptionPane.OK_CANCEL_OPTION,JOptionPane.DEFAULT_OPTION , null, bancos, bancos[0]);
            if (banco >= 0 && banco != 2){
                
            
                String cbu = JOptionPane.showInputDialog(null, "Ingrese CBU", "TRANSFERENCIA", JOptionPane.DEFAULT_OPTION);
                float monto = Float.parseFloat(JOptionPane.showInputDialog(null, "Ingrese MONTO", "TRANSFERENCIA", JOptionPane.DEFAULT_OPTION));
                
                if (monto >= 1){
                    
                    if (banco == 1) {
                    
                        monto = monto;
                        montoR = monto*1.05f;

                    }

                    if (registro.listaClientes.get(op.codigo).cuenta > monto && registro.listaClientes.get(op.codigo).cuenta > montoR){

                        if(banco ==1){
                            Date fecha = new Date();
                            transf = "Transferencia ------ "+String.valueOf(montoR) + " AR$ ----- "+modificarFecha.format(fecha)+
                                            "\nComision: "+monto*0.05 +" AR$ ------ "+"CBU: "+cbu;
                            registro.listaClientes.get(op.codigo).retirar(montoR);
                        } else {
                            Date fecha = new Date();
                            transf = "Transferencia ------ "+String.valueOf(monto) + " AR$ ----- "+modificarFecha.format(fecha)+
                                "\nCBU: "+cbu;
                            registro.listaClientes.get(op.codigo).retirar(monto);
                        }


                        registro.listaClientes.get(op.codigo).ingresarMovimiento(transf);
                        registro.listaClientes.get(op.codigo).ingresarTrasferencia(transf);
                        txtAreaHistorialT.setText(registro.listaClientes.get(op.codigo).mostrarTransferencias());
                    } else {
                        JOptionPane.showMessageDialog(null, "=====>  NO TIENES FONDOS SUFICIENTE", "TRANSFERENCIA", JOptionPane.WARNING_MESSAGE);
                    }
                    
                } else{
                    JOptionPane.showMessageDialog(rootPane, "El monto debe de ser mayor a 1 !!!", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
   
            }
            
        } catch(IllegalArgumentException e1){
            JOptionPane.showMessageDialog(rootPane, e1.getMessage()+"\n\n---->  SOLO NUMEROS !!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e2){
            JOptionPane.showMessageDialog(rootPane, e2.getMessage()+"\n\n---->  DEBES DE INICIAR SESIÓN", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_btnTransferenciaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        
        try{
            Operaciones op = new Operaciones(registro, login);
            this.setVisible(false);
            op.setVisible(true);
            op.repaint();
            op.validate();
        } catch(NullPointerException e1){
            JOptionPane.showMessageDialog(rootPane, e1.getMessage()+"\n\nDebes de iniciar sesion", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaHistorialT;
    // End of variables declaration//GEN-END:variables
}
